<?php

use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('locations')->insert([
            ['code' => 'acc', 'site' => 'acc', 'initial' => 'hoacc', 'name' => 'accounting', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 1
            ['code' => 'asm', 'site' => 'asm', 'initial' => 'hoasm', 'name' => 'asset management', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 2
            ['code' => 'd48', 'site' => 'd48', 'initial' => 'dcd48', 'name' => 'dc 48', 'wilayah' => 'dc', 'regional' => 'dc', 'area' => 'dc', 'address' => 'jl. jakarta no.48', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 3
            ['code' => 'd53', 'site' => 'd53', 'initial' => 'dcd53', 'name' => 'dc 53', 'wilayah' => 'dc', 'regional' => 'dc', 'area' => 'dc', 'address' => 'jl. jakarta no.53', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 4
            ['code' => 'gbg', 'site' => 'gbg', 'initial' => 'dcgbg', 'name' => 'dc gedebage', 'wilayah' => 'dc', 'regional' => 'dc', 'area' => 'dc', 'address' => '-', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 5
            ['code' => 'dcl', 'site' => 'dcl', 'initial' => 'hodcl', 'name' => 'dc fresh', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 6
            ['code' => 'dct', 'site' => 'dct', 'initial' => 'dcdct', 'name' => 'dc telur', 'wilayah' => 'dc', 'regional' => 'dc', 'area' => 'dc', 'address' => '-', 'city' => 'kota sukabumi', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 7
            ['code' => 'fin', 'site' => 'fin', 'initial' => 'hofin', 'name' => 'finance', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 8
            ['code' => 'hrm', 'site' => 'hrm', 'initial' => 'hohrm', 'name' => 'human resources management', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 9
            ['code' => 'it', 'site' => 'it', 'initial' => 'hoit', 'name' => 'information technology', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 10
            ['code' => 'aud', 'site' => 'aud', 'initial' => 'hoaud', 'name' => 'internal audit', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 11
            ['code' => 'ic', 'site' => 'ic', 'initial' => 'hoic', 'name' => 'inventory control', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 12
            ['code' => 'lga', 'site' => 'lga', 'initial' => 'holga', 'name' => 'legal & general affair', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 13
            ['code' => 'mdf', 'site' => 'mdf', 'initial' => 'homdf', 'name' => 'merchandising food', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 14
            ['code' => 'mdn', 'site' => 'mdn', 'initial' => 'homdn', 'name' => 'merchandising non food', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 15
            ['code' => 'opr', 'site' => 'opr', 'initial' => 'hoopr', 'name' => 'operational', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 16
            ['code' => 'oi', 'site' => 'oi', 'initial' => 'hooi', 'name' => 'other income', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 17
            ['code' => 'prc', 'site' => 'prc', 'initial' => 'hoprc', 'name' => 'procurement', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 18
            ['code' => 'pco', 'site' => 'pco', 'initial' => 'hopco', 'name' => 'project control', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 19
            ['code' => 'pcd', 'site' => 'pcd', 'initial' => 'hopcd', 'name' => 'project development', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 20
            ['code' => 'adv', 'site' => 'adv', 'initial' => 'proad', 'name' => 'promotion & advertising', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 21
            ['code' => 'sdd', 'site' => 'sdd', 'initial' => 'hosdd', 'name' => 'sales development', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 22
            ['code' => 'smo', 'site' => 'smo', 'initial' => 'hosmo', 'name' => 'simo', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 23
            ['code' => 'sdv', 'site' => 'sdv', 'initial' => 'hosdv', 'name' => 'store development', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'], // 24
            ['code' => 'tax', 'site' => 'tax', 'initial' => 'hotax', 'name' => 'tax', 'wilayah' => 'ho', 'regional' => 'ho', 'area' => 'ho', 'address' => 'jl. soekarno hatta no. 236', 'city' => 'kota bandung', 'email' => '-', 'dc_support' => '-', 'telp' => '-', 'created_by' => 'superadmin', 'updated_by' => 'superadmin', 'created_at' => '2025-09-16 11:23:30', 'updated_at' => '2025-09-16 11:23:30'] // 25
        ]);
    }
}